import pandas as pd
import random 

employee_db=pd.read_csv("../insert_to_mysql/employee_data.csv")
employee_db.head()

first_names = [
    "Ahmed",
    "Youssef",
    "Mohamed",
    "Omar",
    "Hassan",
    "Salma",
    "Fatima",
    "Khadija",
    "Aya",
    "Meryem",
    "Othmane",
    "Hamza",
    "Yahya",
    "Amine",
    "Youssef",
    "Omar",
    "Kawtar",
    "Kaoutar",
    "Hiba",
    "Hajar",
    "Mohammed Amine",
    "Taha",
    "Rachida",
    "Aziza",
    "Adam",
    "Fatima Ezzahra ",
    "Noha",
    "Zineb",
    "Rania",
    "Malak",
    "Jamila",
    "Khaoula",
]

last_names = [
    "Alaoui",
    "Benali",
    "El Idrissi",
    "Bennani",
    "Amrani",
    "Lahlou",
    "Tazi",
    "Berrada",
    "El Fassi",
    "Ouazzani",
    "Skalli",
    "Bachri",
    "El Yousfi",
    "Benchikh",
    "Amine",
    "Metouali",
    "Salhi",
    "Banoune",
    "Tahiri",
    "Kibala",
    "Radi",
    "Mansour",
    "Barghoud",
    "Bate",
    "Fadili",
    "Moufkir ",
    "Fakhir",
    "Dadi",
    "Mansar",
    "Farissi",
    "Jamal",
    "Eddoughmi",
    "Oufkir",
]


city_mapping = {
    "Montgomery": "Casablanca",
    "Fayetteville": "Rabat",
    "Washington": "Tanger",
    "Nashville": "Marrakech",
    "Arvada": "Agadir",
    "Manchester": "Sale",
    "Glendale": "Fes",
    "Louisville": "Meknes",
    "Anchorage": "Tetouan",
    "Savannah": "Kenitra",
    "Panama City": "Essaouira",
    "Oklahoma City": "Oujda",
    "Panama City Beach": "El Jadida",
    "Oakland": "Safi",
    "Glean Burnie": "Beni Mellal",
    "Fremont": "El Hoceima",
    "Annapolis": "Ouarzazate",
    "Hayward": "Guelmim",
    "Berkeley": "Nador",
    "Pooler": "Khourubga",
    "Pasadena": "Sefrou",
    "Lynn Haven": "Berrechid",
    "Edmond": "Settat",
    "San leandro": "Fnideq",
    "Livermore": "Laayoune",
    "Union City": "MideltDakhla",
    "Moore": "Berkane",
    "Severne": "Ifrane",
    "Norman": "Sidi Kacem",
    "Burlington": "Taaroudant",
    "Quincy": "El Kelaa des Sraghna",
    "Rutland": "Ben Guerir",
    "Groton": "Guercif",
    "Severna Park": "Mohammedia",
    "Farmington": "Tan Tan",
    "Edgwater": "Tiflet",
    "Cupernito": "Sidi Sliame",
    "Midwest City": "Azrou",
    "Castro Valley": "Oued Zem",
    "Hartford": "Tiznit",
    "Litchfield Park": "Midelt",
    "Saint Albans City": "Taourirt",
    "Medford": "Chefchaouen",
    "Cambridge": "Larache",
    "Hanover": "Taza",
    "Edgewater": "Asilah",
    "Aurora": "Ifrane",
    "Dartmouth": "Khenifra",
    "Santa Rosa": "Ksar El Kebir",
    "New Bedford": "Fnideq",
    "Khourubga": "Khourubga",
    "Millersville": "M'diq",
    "NULL": "Martil",
    "Glen Burnie": "Ouezzane",
    "Williston": "Beni Mellal",
    "West Windsor": "Kasba Tadla",
    "Lyndon": "Fquih Ben Salah",
    "Burke": "Azilal",
    "Arnold": "Khemisset",
    "Bourne": "Tiflet",
    "Greenfield": "Rommani",
    "Thunderbolt": "Sidi Slimane",
    "Reading": "Sidi Yahya El Gharb",
    "Kenai": "Souk El Arbaa",
    "Lincoln": "Mechra Bel Ksiri",
    "Essex": "Youssoufia",
    "Fountain": "Chichaoua",
    "Wheat Ridge": "Tinghir",
    "Bakersfield": "Zagora",
    "Gardena": "Errachidia",
    "Springfield": "Erfoud",
    "Chester": "Rissani",
    "Pueblo": "Figuig",
    "Odenton": "Bouarfa",
    "Stowe": "Jerada",
    "San Lorenzo": "Ahfir",
    "Ione": "Saadia",
    "Santa Cruz": "Zaio",
    "Severn": "Driouch",
    "Palmer": "Midar",
    "Linda": "Imzouren",
    "Morristown": "Beni Bouayach",
    "Bristol": "Targuist",
    "Telluride": "Ksar Sghir",
    "Mesa": "Gueznaia",
    "West Sacramento": "Zeghanghane",
    "San Jose": "Selouane",
    "Lunenburg": "Arekmane",
    "Saint Matthews": "Bni Ansar",
    "San Leandro": "Ras El Ma",
    "Tybee Island": "Aknoul",
    "Waddell": "Tahla",
    "Brockton": "Oued Amlil",
    "Del City": "Imouzzer Kandar",
    "Freetown": "Bhalil",
    "Huntington": "El Hajeb",
    "Deale": "Agourai",
    "Westmore": "Ain Taoujdate",
    "Chico": "Mrirt",
    "Mammoth Lakes": "Er-Rich",
    "Garden City": "Goulmima",
    "Cupertino": "Tinjdad",
    "Waitsfield": "Jorf",
    "Brooklyn Park": "Kalaat M'Gouna",
    "Tampa": "Boumalne Dades",
    "West Brattleboro": "Skoura",
    "Revere": "Agdz",
    "Prospect": "Demnate",
    "Orange": "Boujniba",
    "North Little Rock": "Hattane",
    "Woodford": "Oulmes",
    "Haverhill": "Ain El Aouda",
    "Dennis": "Skhirat",
    "Richford": "Temara",
    "Alburgh": "Bouznika",
    "Escondido": "Benslimane",
    "Hingham": "Tit Mellil",
    "Port Charlotte": "Mediouna",
    "Barre": "Nouaceur",
    "Merritt Island": "Deroua",
    "South Burlington": "Ben Ahmed",
    "Birmingham": "El Borouj",
    "Piedmont": "Oulad Teima",
    "McCrory": "Inezgane",
    "Marlborough": "Dcheira El Jihadia",
    "Braintree": "Ait Melloul",
    "Mansfield": "Lqliiaa",
    "Williamstown": "Massa",
    "Davis": "Sidi Ifni",
    "Calhoun": "Assa",
    "Newark": "Zag",
    "Laurel": "Tata",
    "Baltimore": "Akka",
    "Waltham": "Bouizakarne",
    "Palm Bay": "Tarfaya",
    "West River": "Boujdour",
    "Woodbury": "Dakhla",
    "Rancho Cordova": "Smara",
    "Selma": "Akhfenir",
    "Fort Collins": "El Marsa",
    "Charlotte": "Tahannaout",
    "Stratton": "Amizmiz",
    "Fresno": "Ait Ourir",
    "Saint Albans Town": "Lalla Takerkoust",
    "Millis": "Moulay Yacoub",
    "Peoria": "Missour",
    "Guilford": "Outat El Haj",
    "Riverview": "Boulemane",
    "Atascadero": "Ain Bni Mathar",
    "North Reading": "Tendrara",
    "Pleasanton": "Matarka",
    "Brookline": "Tafraout",
    "Brentwood": "Imi n'Tanoute",
    "Greeley": "Echemmaia",
    "Dracut": "Sebt Gzoula",
    "Northfield": "Oualidia",
    "Brighton": "Sidi Bennour",
    "Beverly Hills": "Zemamra",
    "Richmond": "Azemmour",
    "Eureka": "Bir Jdid",
    "Hinesburg": "Sidi Smail",
    "Proctor": "Sidi Allal El Bahraoui",
    "Montevallo": "Sidi Bouzid",
    "Worcester": "Ain Harrouda",
    "Woodland": "Sidi Rahal",
    "Roseville": "Had Soualem",
    "Youngstown": "Karia Ba Mohamed",
    "Port Wentworth": "Tissa",
    "Crofton": "Taounate",
    "Wolcott": "Rhaf Sai",
    "Thetford": "Thar Es-Souk",
    "Randolph": "Jorf El Melha",
    "Chefchaouen": "Chefchaouen",
    "Aspen": "Ain Dfali",
    "Bethany": "Mhaya",
    "Mexico Beach": "Sebaa Aiyoun",
    "Watertown": "Ain Cheggag",
    "Southport": "Ribat El Kheir",
    "Boulder": "El Menzel",
    "Guthrie": "Bir Tam-Tam",
    "Salinas": "Ghafsai",
    "Highgate": "Bni Walid",
    "Middlebury": "Oulad Ayad",
    "Milford": "Dar Ould Zidouh",
    "Barnard": "Bradia",
    "Vershire": "Sidi Jaber",
    "Shelburne": "Zaouiat Cheikh",
    "Sacramento": "El Ksiba",
    "Littleton": "Aghbala",
    "Peabody": "Ouaouizeght",
    "Attleboro": "Afourar",
    "Fruita": "Bzou",
    "Colchester": "Foum Jamaa",
    "Salisbury": "Sidi Rahal Chatai",
    "Jeffersontown": "Ait Daoud",
    "Plantation": "Tamanar",
    "Lowell": "Smimou",
    "Tewksbury": "Ounagha",
    "Easthampton": "Talmest",
    "Medway": "Aklim",
    "Bolton": "Madagh",
    "Wakefield": "Boughriba",
    "Wareham": "Chouihia",
    "Redlands": "Tafoughalt",
    "Sheffield": "Zegzel",
    "Fairlee": "Sidi Boubker",
    "Hubbardston": "Touissit",
    "Davidsonville": "Aourir",
    "Magalia": "Taghazout",
    "Billerica": "Tamraght",
    "San Diego": "Imsouane",
    "Agawam": "Sebt El Guerdane",
    "O'Neals": "Ouled Berhil",
    "Los Angeles": "Aoulouz",
    "Van Buren": "Taliouine",
    "Easton": "Igli",
    "Pawlet": "Fam El Hisn",
    "Pittsfield": "Icht",
    "Westminster": "Foum Zguid",
    "Hyde Park": "Tazenakht",
    "Somerset": "Skoura Ahl El Oust",
    "Smartsville": "Alnif",
    "Salem": "Mellab",
    "McKinleyville": "Tourza",
    "Pioneer": "Tinejdad",
    "Wheelock": "Aoufous",
    "Goodlettsville": "Imilchil",
    "Holyoke": "Agoudal",
    "Lithia": "Anergui",
    "Noble": "Tillouguite",
    "Tyndall Air Force Base": "Zaouiat Ahansal",
    "Paso Robles": "Tabant",
    "Beverly": "Ait M'hamed",
    "Methuen": "Ouzoud",
    "King City": "Tanant",
    "Pike Road": "Beni Ayat",
    "Marysville": "Souk Sebt Oulad Nemma",
    "Wilmington": "Had Boumoussa",
    "Arlington": "Krouchen",
    "Fortuna": "El Kbab",
    "Hartland": "Kerrouchen",
    "Mount Tabor": "Boumia",
    "Mountain View": "Tounfite",
    "Homer": "Itzer",
    "Madera": "Zaida",
    "Evergreen": "Aguelmous",
    "Brimfield": "Moulay Bouazza",
    "El Cerrito": "Ouaoumana",
    "Foxborough": "Sidi Lamine",
    "Concord": "Kehf Nsour",
    "Pelham": "Sebt Jahjouh",
    "Soda Springs": "Haj Kaddour",
    "Jackson": "Boufakrane",
    "Conway": "Sidi Taibi",
    "Newton": "Mehdia",
    "Franklin": "Sidi Yahya Zaer",
    "Yarmouth": "Shoul",
    "South Lake Tahoe": "Arbaoua",
    "Norton": "Lalla Mimouna",
    "Whitmore": "Moulay Bousselham",
    "Carson": "Khenichet",
    "Crownsville": "Zirara",
    "Athol": "Had Kourt",
    "Melbourne Beach": "Mjara",
    "Greensboro": "Brikcha",
    "Soldotna": "Moqrisset",
    "Falmouth": "Zoumi",
    "Walpole": "Bab Berred",
    "Plymouth": "Bab Taza",
    "Pittsford": "Bni Gorfet",
    "Belchertown": "Souk Tolba",
    "Danville": "Dar Gueddari",
    "Castleton": "Ben Mansour",
    "Vallejo": "Mograne",
    "Soquel": "Ameur Seflia",
    "Holbrook": "Sidi Mohamed Lahmar",
    "Vergennes": "Mnasra",
    "Needham": "Benmansour",
    "Everett": "Bahouda",
    "Redding": "Oulad Tayeb",
    "Winchester": "Sidi Harazem",
    "Marblehead": "Ain Chkef",
    "Swanton": "Oulad Jamaa",
    "Lynnfield": "Karia",
    "Maidstone": "Bni Sidel",
    "Town of Rockingham": "Boudinar",
    "Hadley": "Temsamane",
    "Alameda": "Ben Taieb",
    "Charlton": "Dar El Kebdani",
    "Scituate": "Kassita",
    "Jessup": "Ksar El Majaz",
    "The Village": "Taghramt",
    "Grass Valley": "Belyounech",
    "Wheatland": "Oued Laou",
    "Middleborough": "Stehat",
    "Melrose": "Bou Ahmed",
    "Sutter Creek": "Jebha",
    "Spencer": "Asjen",
    "Foresthill": "Ain Dorij",
    "Ludlow": "Sidi Redouane",
    "Linthicum Heights": "Teroual",
    "Ardmore": "Bni Hadifa",
    "Shaftsbury": "Rouadi",
    "Santa Clara": "Senada",
    "Dublin": "Tamassint",
    "Capitola": "Tifariti",
    "Olivehurst": "Mahbes",
    "Mount Juliet": "Guelta Zemmur",
    "Sebastopol": "Oum Dreyga",
    "Lexington": "Bir Gandouz",
    "Gardner": "Tichla",
    "Ashland": "Aousserd",
    "Sun City Center": "Zghenghen",
    "Dedham": "Taza Haut",
    "Hanford": "Khemis Sahel",
    "Antioch": "My Yacoub",
    "San Luis Obispo": "N'Zalat Bni Amar",
    "Tyngsborough": "Oulad Ziane",
    "Boxborough": "Lbir Jdid",
    "Fall River": "Imouzzer",
    "Barnstable": "Bni Makada",
    "Milton": "Charf",
    "Riva": "Souani",
    "Chelmsford": "Gzenaya",
    "Newport": "Aouama",
    "Twentynine Palms": "Hjar Nhal",
    "Morro Bay": "Al Arroui",
    "Lawrence": "Beni Ensar",
    "Vacaville": "Zghanghan",
    "Shelburne Falls": "Jaadar",
    "New Haven": "Ihddaden",
    "Lynn": "Iksane",
    "Oak Bluffs": "Beni Chiker",
    "Fairfield": "Farkhana",
    "Aquinnah": "Tiztoutine",
    "Poultney": "Afso",
    "Oakhurst": "Hassi Berkane",
    "Pismo Beach": "Oulad Settout",
    "Chelsea": "Bni Oukil",
    "Woburn": "Chbanat",
    "Oroville": "Ayt Youssef Ou Ali",
    "Longmeadow": "Ajdir",
    "Calera": "Tsaft",
    "Belvidere": "Izaoumen",
    "Wilbraham": "Trougout",
    "Weathersfield": "Tafersit",
    "East Longmeadow": "Iferni",
    "Marshfield": "Ijermaouas",
    "Fitchburg": "Ameur",
    "Webster": "Sidi Bou Othmane",
    "Bloomingdale": "Skhour Rehamna",
    "Saint Johnsbury": "Sidi Abdallah",
    "Moretown": "Nzalat",
    "Blue Lake": "Ouahat Sidi Brahim",
    "Harrah": "Tameslouht",
    "Bethel": "Ouirgane",
    "Grand Junction": "Asni",
    "Nichols Hills": "Imlil",
    "Holden": "Ourika",
    "Montpelier": "Setti Fatma",
    "Gambrills": "Oukaimeden",
    "Auburn": "Tazart",
    "Mountain Village": "Touama",
    "Yucaipa": "Tidili Mesfioua",
    "Somerville": "Zerkten",
    "Gloucester": "Abadou",
    "Carlsbad": "Amezmiz",
    "Hurstbourne Acres": "Azgour",
    "Punta Gorda": "Anougal",
    "Indian Springs Village": "Dar Jamaa",
    "Castaic": "Oulad Hassoune",
    "Tollhouse": "Oulad Mtaa",
    "North Beach": "Sidi Zouine",
    "Duxbury": "Loudaya",
    "South Hadley": "Mejjat",
    "Suisun City": "Guemassa",
    "Inverness": "M'Zouda",
    "Dummerston": "Zaouia Annahlia",
    "Boxford": "Imindounit",
    "Guildhall": "Adassil",
    "Saugus": "Assif El Mal",
    "Warr Acres": "Majjat",
    "Chicopee": "Sidi Mokhtar",
    "Merrimac": "Oulad Boumia",
    "Fairfax": "Ahil",
    "Baldwin Park": "Ighoud",
    "Pueblo West": "Jdour",
    "Harwich": "Ayir",
    "Gibson Island": "El Beddouza",
    "Windsor": "Lamsid",
    "Westport": "Khatazakane",
    "Evans": "Lamrasla",
    "Truckee": "Laghiat",
    "Westford": "Saadla",
    "Choctaw": "Sidi Tiet",
    "East Haven": "Dar Si Aissa",
    "Rohnert Park": "Sidi Aissa",
    "Newfane": "Lahdar",
    "Underhill": "Lamsabih",
    "Middleton": "Atouabet"
}
postal_codes = {
    "Casablanca": 20220,
    "Rabat": 11025,
    "Tanger": 90053,
    "Marrakech": 40000,
    "Agadir": 80000,
    "Sale": 11000,
    "Fes": 30000,
    "Meknes": 50010,
    "Tetouan": 93000,
    "Kenitra": 14110,
    "Essaouira": 44000,
    "Oujda": 60010,
    "El Jadida": 24010,
    "Safi": 46000,
    "Beni Mellal": 23000,
    "El Hoceima": 32000,
    "Ouarzazate": 45000,
    "Guelmim": 81000,
    "Nador": 62000,
    "Khourubga": 25000,
    "Sefrou": 31000,
    "Berrechid": 26100,
    "Settat": 26000,
    "Fnideq": 93200,
    "Taourirt": 65000,
    "Midelt": 54350,
    "Berkane": 60300,
    "Ifrane": 53000,
    "Sidi Kacem": 16000,
    "Taaroudant": 83000,
    "El Kelaa des Sraghna": 43000,
    "Ben Guerir": 43150,
    "Guercif": 37000,
    "Mohammedia": 28810,
    "Tan Tan": 82000,
    "Tiflet": 15400,
    "Sidi Sliame": 14200,
    "Azrou": 53100,
    "Oued Zem": 25200,
    "Tiznit": 85000,
    "Dakhla": 73000,
    "Laayoune": 70000,
    "Chefchaouen": 91000,
    "Larache": 92000,
    "Taza": 35000,
}

cin_mapping = {
    "Casablanca": "BJ",
    "Rabat": "AG",
    "Tanger": "KB",
    "Marrakech": "EE",
    "Agadir": "JK",
    "Sale": "AB",
    "Fes": "CC",
    "Meknes": "DN",
    "Tetouan": "L",
    "Kenitra": "G",
    "Essaouira": "N",
    "Oujda": "F",
    "El Jadida": "M",
    "Safi": "HH",
    "Beni Mellal": "I",
    "El Hoceima": "R",
    "Ouarzazate": "P",
    "Guelmim": "JA",
    "Nador": "SA",
    "Khouribga": "Q",
    "Sefrou": "CB",
    "Berrechid": "WA",
    "Settat": "W",
    "Fnideq": "LF",
    "Taourirt": "FB",
    "Midelt": "VA",
    "Berkane": "FA",
    "Ifrane": "DB",
    "Sidi Kacem": "GK",
    "Taaroudant": "JC",
    "El Kelaa des Sraghna": "Y",
    "Ben Guerir": "EA",
    "Guercif": "ZG",
    "Mohammedia": "T",
    "Tan Tan": "JF",
    "Tiflet": "XA",
    "Sidi Sliame": "GA",
    "Azrou": "DA",
    "Oued Zem": "QA",
    "Tiznit": "JE",
    "Dakhla": "OD",
    "Laayoune": "SH",
    "Chefchaouen": "LC",
    "Larache": "LA",
    "Taza": "Z",
}
street_types=[
    "Avenue",
    "Rue",
    "Boulevard",
    "Lotissement",
    "Hay",
    "Residence"
]
street_name=[
    "Hlioua",
    "Bernoussi",
    "Salam",
    "Mohammed V",
    "Hassan II",
    "Al Massira",
    "Centrale",
    "Zerktouni",
    "Al Qods",
    "Al Houda",
    "El Fadl",
]

del employee_db["ADDRESS_LINE2"]
del employee_db["STATE"]


name_mapping={}
for name in employee_db["AGENT_NAME"].unique():
    name_mapping[name]=random.choice(first_names)+" "+random.choice(last_names)

employee_db["AGENT_NAME"]=employee_db["AGENT_NAME"].map(name_mapping)


employee_db["CITY"]=employee_db["CITY"].replace(city_mapping)


name_mapping={}
for name in employee_db["AGENT_NAME"].unique():
    name_mapping[name]=random.choice(first_names)+" "+random.choice(last_names)

employee_db["AGENT_NAME"]=employee_db["AGENT_NAME"].map(name_mapping)

address_mapping={}
for address in employee_db["ADDRESS_LINE1"]:
    address_mapping[address]=str(random.randrange(1,20))+" "+random.choice(street_types)+" "+random.choice(street_name)
    
employee_db["ADDRESS_LINE1"]=employee_db["ADDRESS_LINE1"].map(address_mapping)


employee_db["POSTAL_CODE"]=employee_db["CITY"].map(postal_codes)
employee_db.to_csv("../data/agent.csv")
